server:
  port: 8081

db:
  username: root
  password: root
  host: localhost
  port: 3306
  dbname: test
  charset: utf8mb4
  maxidleconns: 50
  maxlifetime: 600
  maxopenconns: 2048
  connTimeout: 300

logger:
  level: debug
  showsql: true

auth:
  jwt:
    secret: "secret"
    cookie:
      name: "jwt_token"
